npmRegistryServer: "http://localhost:4873"

unsafeHttpWhitelist:
  - localhost

packageExtensions: {
  "@aws-amplify/deployed-backend-client@*": {
    dependencies: {
      "@aws-sdk/client-cloudformation": "*",
      "@aws-sdk/client-amplify": "*",
      "@aws-sdk/client-s3": "*"
    }
  },
  "@aws-amplify/backend-output-schemas@*": {
    dependencies: {
      "zod": "*"
    }
  }
}
